drop table if exists friends, likes, film_genres, users, films cascade;

create table if not exists users (
    id int generated by default as identity primary key,
    name varchar(255) not null,
    login varchar(255) not null,
    email varchar(255),
    birthday date,
    unique (login),
    unique (email)
);

create table if not exists mpa (
    id int generated by default as identity primary key,
    name varchar(255) not null
);

create table if not exists genres (
    id int generated by default as identity primary key,
    name varchar(255) not null
);

create table if not exists films (
    id int generated by default as identity primary key,
    name varchar(255) not null,
    description varchar(200),
    release_date date,
    duration int,
    mpa_id int references mpa (id)
);

create table if not exists likes (
    film_id integer not null references films (id),
    user_id integer not null references users (id),
    primary key(film_id, user_id)
);

create table if not exists friends (
    user_id integer not null references users (id),
    friend_id integer not null references users (id),
    primary key (user_id, friend_id)
);

create table if not exists film_genres (
    film_id integer not null references films (id),
    genre_id integer not null references genres (id),
    primary key (film_id, genre_id)
);
